<?xml version="1.0"?>
<robot name="neptr" xmlns:xacro="http://ros.org/wiki/xacro">
  <xacro:property name="leg_length" value="0.5"/>
  <xacro:property name="link_width" value="0.05"/>
  
  <link name="base_link">
    <visual>
      <geometry>
        <box size="0.2 0.2 0.1"/>
      </geometry>
      <material name="blue"/>
    </visual>
  </link>

  <!-- Hip Joint -->
  <joint name="hip_joint" type="revolute">
    <parent link="base_link"/>
    <child link="thigh"/>
    <origin xyz="0 0 0.05" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <limit effort="10" velocity="2" lower="-1.57" upper="1.57"/>
  </joint>

  <link name="thigh">
    <visual>
      <geometry>
        <box size="0.05 0.05 ${leg_length/2}"/>
      </geometry>
      <material name="red"/>
    </visual>
  </link>
</robot>